version: '3.8'

services:
  node_a:
    image: postgres_replication-rework_node_a:latest
    container_name: node_a
    build:
      context: ./node_a
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      pg_net:
        ipv4_address: 172.20.0.10
    security_opt:
      - label=disable
    
networks:
  pg_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24