version: '3.8'

services:
  node_a:
    image: postgres_replication-rework_node_a:latest
    container_name: node_a
    build:
      context: ./node_a
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      pg_net:
        ipv4_address: 172.20.0.10
    security_opt:
      - label=disable
  node_b:
    image: postgres_replication-rework_node_b:latest
    container_name: node_b
    build:
      context: ./node_b
    depends_on:
      node_a:
        condition: service_healthy
    ports:
      - "5435:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      pg_net:
        ipv4_address: 172.20.0.20
    security_opt:
      - label=disable
  node_c:
    image: postgres_replication-rework_node_c:latest
    container_name: node_c
    build:
      context: ./node_c
    depends_on:
      node_b:
        condition: service_healthy
    ports:
      - "5436:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - PGENCODING=UTF8
      - PGLOCALE=en_US.UTF8
      - PGUSERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      pg_net:
        ipv4_address: 172.20.0.30
    security_opt:
      - label=disable
    
networks:
  pg_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24